### ISSUE TITLE
Not able to create check

### ISSUE THREAD

**Issue by sumityadav6541** [onfido/api-java-client#5] opened 2019-02-22 07:57 UTC
while trying to create check using
`api.createCheck(applicantId, check);`

getting following error-:

> Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 621 path $.reports[0].documents
at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:79)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)

**Comment by ciaran16** [comment] 2019-02-22 14:55
Hi @sumityadav6541, thanks for raising an issue. Could you give some more context about what you're trying to do? What sort of check? Any more code would be useful.

**Comment by sumityadav6541** [comment] 2019-02-26 07:27
@ciaran16 I have attached the file which i am trying. just change the extension to .java from .txt and run it with required dependencies from the client project and that should give you the error.
[TestApp.txt](https://github.com/onfido/api-java-client/files/2904186/TestApp.txt)

**Comment by sumityadav6541** [comment] 2019-02-27 11:13
@ciaran16 any update on this? let me know if you need anything else to reproduce the issue.

**Comment by ciaran16** [comment] 2019-02-27 12:56
Hi @sumityadav6541 , thanks for the code sample, I managed to reproduce.

The issue is caused by the API returning an empty object `{}` for the `documents` field on reports when creating a document check, whereas it should be an empty array. The issue is fixed but unfortunately won't be released for another 2 weeks.

**Comment by ciaran16** [comment] 2019-03-27 11:54
Hi @sumityadav6541, this should be working now, so I'm going to close this issue. Feel free to reopen if something's still not working.

**Closed as completed by ciaran16** 2019-03-27 11:54 UTC
